PROCEDURE PP_CARGAR_DATOS IS
--
BEGIN
:BENCA.S_USUARIO := USER;
:BENCA.S_FECHA := TO_CHAR(SYSDATE, 'DD-MM-YYYY');



:BENCA.S_DESC_EMPRESA := :PARAMETER.P_DESC_EMPRESA;
:BENCA.S_DESC_SUCURSAL := :PARAMETER.P_DESC_SUCURSAL;
:BENCA.S_DESC_PROGRAMA := :PARAMETER.P_DESC_PROGRAMA;
:BENCA.S_PROGRAMA := :PARAMETER.P_PROGRAMA;
--




BEGIN
SELECT CONF_MON_US, CONF_MON_LOC,CONF_IND_OPERADOR
INTO :PARAMETER.P_MON_US, :PARAMETER.P_MON_LOC, :PARAMETER.P_IND_OPERADOR
FROM GEN_CONFIGURACION
where conf_empr=:parameter.p_empresa;

IF :PARAMETER.P_IND_OPERADOR = 'N' THEN
SET_ITEM_PROPERTY('BDOC.S_ETIQ_OPERADOR',DISPLAYED,PROPERTY_FALSE);
SET_ITEM_PROPERTY('BDOC.DOC_OPERADOR',DISPLAYED,PROPERTY_FALSE);
SET_ITEM_PROPERTY('BDOC.DOC_OPERADOR',ENABLED,PROPERTY_FALSE);
SET_ITEM_PROPERTY('BDOC.DOC_OPERADOR',NAVIGABLE,PROPERTY_FALSE);
ELSE
SET_ITEM_PROPERTY('BDOC.S_ETIQ_OPERADOR',DISPLAYED,PROPERTY_TRUE);
SET_ITEM_PROPERTY('BDOC.DOC_OPERADOR',DISPLAYED,PROPERTY_TRUE);
SET_ITEM_PROPERTY('BDOC.DOC_OPERADOR',ENABLED,PROPERTY_TRUE);
SET_ITEM_PROPERTY('BDOC.DOC_OPERADOR',NAVIGABLE,PROPERTY_TRUE);
END IF;
EXCEPTION
WHEN NO_DATA_FOUND THEN
message('No fue cargada la tabla de configuración general de sistemas!.');PAUSE;
do_key('exit');--EXIT_FORM;
WHEN FORM_TRIGGER_FAILURE THEN
RAISE FORM_TRIGGER_FAILURE;
WHEN OTHERS THEN
PL_EXHIBIR_ERROR_PLSQL;
END;



--
SELECT MON_DEC_IMP,
MON_SIMBOLO
INTO :PARAMETER.P_CANT_DECIMALES_LOC,
:PARAMETER.P_LOC_SIMBOLO
FROM GEN_MONEDA
WHERE MON_EMPR = :PARAMETER.P_EMPRESA
AND MON_CODIGO = :PARAMETER.P_MON_LOC;
--
SELECT ----------------------------------------------
CONF_RECIBO_CNCR_EMIT ,
CONF_RECIBO_CNCR_REC ,
CONF_RECIBO_CADCLI_EMIT ,
----------------------------------------------
CONF_NOTA_CR_EMIT ,
CONF_NOTA_CR_REC ,
----------------------------------------------
CONF_FACT_CR_EMIT ,
CONF_FACT_CR_REC ,
CONF_NOTA_DB_EMIT ,
CONF_NOTA_DB_REC ,
----------------------------------------------
CONF_NOTA_CR_REC_H ,
CONF_FACT_CR_REC_H ,
CONF_FACT_CO_REC_H ,
CONF_FACT_COMPRA_H ,
CONF_NOTA_DB_REC_H ,
----------------------------------------------
CONF_RECIBO_CNCR_REC_H ,
CONF_RECIBO_CAN_FAC_REC_H ,
----------------------------------------------
CONF_ADELANTO_CLI ,
CONF_RECIBO_CAN_FAC_EMIT ,
CONF_RECIBO_CAN_FAC_REC ,
CONF_RECIBO_CADPRO_REC ,
CONF_ADELANTO_PRO ,
CONF_TMOV_ORDEN_COMPRA ,
CONF_NOTA_DB_EMIT_PROV ,
CONF_CONCEPTO_COBRO ,
CONF_CONCEPTO_PAGO ,
CONF_CONC_CADCLI ,
CONF_CONC_CADPRO
----------------------------------------------
INTO :BCONF.CONF_RECIBO_CNCR_EMIT ,
:BCONF.CONF_RECIBO_CNCR_REC ,
:BCONF.CONF_RECIBO_CADCLI_EMIT ,
----------------------------------------------
:BCONF.CONF_NOTA_CR_EMIT ,
:BCONF.CONF_NOTA_CR_REC ,
----------------------------------------------
:BCONF.CONF_FACT_CR_EMIT ,
:BCONF.CONF_FACT_CR_REC ,
:BCONF.CONF_NOTA_DB_EMIT ,
:BCONF.CONF_NOTA_DB_REC ,
----------------------------------------------
:BCONF.CONF_NOTA_CR_REC_H ,
:BCONF.CONF_FACT_CR_REC_H ,
:BCONF.CONF_FACT_CO_REC_H ,
:BCONF.CONF_FACT_COMPRA_H ,
:BCONF.CONF_NOTA_DB_REC_H ,
----------------------------------------------
:BCONF.CONF_RECIBO_CNCR_REC_H ,
:BCONF.CONF_RECIBO_CAN_FAC_REC_H ,
----------------------------------------------
:BCONF.CONF_ADELANTO_CLI ,
:BCONF.CONF_RECIBO_CAN_FAC_EMIT ,
:BCONF.CONF_RECIBO_CAN_FAC_REC ,


:BCONF.CONF_RECIBO_CADPRO_REC ,
:BCONF.CONF_ADELANTO_PRO ,
:BCONF.CONF_TMOV_ORDEN_COMPRA ,
:BCONF.CONF_NOTA_DB_EMIT_PROV ,

:BCONF.CONF_CONCEPTO_COBRO ,
:BCONF.CONF_CONCEPTO_PAGO ,
:BCONF.CONF_CONC_CADCLI ,
:BCONF.CONF_CONC_CADPRO

FROM FIN_CONFIGURACION
WHERE CONF_EMPR = :PARAMETER.P_EMPRESA;



--
--buscar el tipo de movimiento despacho
:BCONF.TMOV_DESPACHO:=FL_TIPO_MOV('DESPACHO',:parameter.p_empresa);
--
--buscar el tipo de movimiento despacho
:BCONF.TMOV_FACT_CR_REC_AJUSTE:=FL_TIPO_MOV('FACT.CRED.REC.AJUSTE',:parameter.p_empresa);
--
--buscar el tipo de movimiento despacho
:BCONF.TMOV_NOTA_CR_REC_AJUSTE:=FL_TIPO_MOV('NOTA.CRED.REC.AJUSTE',:parameter.p_empresa);
--
--buscar el tipo de movimiento despacho
:BCONF.TMOV_FACT_CR_EMIT_AJUSTE:=FL_TIPO_MOV('FACT.CRED.EMIT.AJUS.',:parameter.p_empresa);
--
--buscar el tipo de movimiento despacho
:BCONF.TMOV_NOTA_CR_EMIT_AJUSTE:=FL_TIPO_MOV('NOTA CRED.EMIT.AJUS.',:parameter.p_empresa);
--

PP_ESTABLECER_FORMATO;


BREAK;





END;