OBTENER LOS REGISTROS SELECCIONADOS
   CLAVE STK DOCUMENTO
 
CREAR UNA COLECCION DE DOCUMENTOS_COMBUSTIBLE

AGREGAR
  C001 STK_DOCUMENTO >> docu_clave
  
DE TODAS LAS CLAVES AGRUPAR SEGUN EL STK_DOCUMENTO_DET
LOS ARTICULOS Y SUS CANTIDADES
